### ISSUE TITLE
Hey there...I read through your profile and I guess we are on the same page...Please I just started the basics of HTML down to “comment out HTML”..My question is how do I put that in practice practically as a beginner to ensure I’m on the tight track? Please I need your help on this thanks in advance!!

### ISSUE THREAD

**Issue by Code1069** [Explosion-Scratch/Explosion-scratch#1]

**Comment by Explosion-Scratch** [comment]
I'm not quite sure what you mean by 'the tight track' but commenting out html is simple: ```<!-- Your comment goes here -->``` I often use comments when I want to remove sections of code that I need in the future. I just put ```<!--``` before the code and ```-->``` after. For some HTML refrence I'd reccoment w3schools. Also you really can't make anything out of just HTML or just CSS so if you're learning one you should definitely learn the other. If you have any more questions feel free to ask! :)

**Comment by Code1069** [comment]
> I'm not quite sure what you mean by 'the tight track' but commenting out html is simple: ```<!-- Your comment goes here -->``` I often use comments when I want to remove sections of code that I need in the future. I just put ```<!--``` before the code and ```-->``` after. For some HTML refrence I'd reccoment w3schools. Also you really can't make anything out of just HTML or just CSS so if you're learning one you should definitely learn the other. If you have any more questions feel free to ask! :)

I'm sorry took me so long to reply, just seeing this.. What I mean by being on the right track is that, I just started and I really want to be sure if I'm on the right track, beside that if I'm to start coding how do I go about that like I mean if I'm to put into practice what I've learnt, how do I go about it.?Lastly how do I creat a website?

**Comment by Explosion-Scratch** [comment]
Sure! So here are some things that I found extremely helpful and wish that I'd learned earlier (sorry it sounds click-baity):
# CSS:
### Setting CSS variables
You can set variables in CSS and change them all at once. This is super useful for having a color scheme. It makes it easy to change and super easy to add something like dark mode.
```css
::root {
    --variable-name: anything you want, a color, a list of stuff, anything;
}

p {
    color: var(--variable-name);
}
```
### Transitions
These make anything you make look _so_ much better:
```css
p {
    transition-duration: 0.5s;
}
```
or if you only want to transition certain elements:
```css
p {
    transition: color, background-color 0.5s ease-in;
}
```
And then you can animate the colors of the whole webpage:
```css
* {
    transition: color, background-color, box-shadow 0.5s;
}
```
### Learn the checkbox hack
This makes it so that you can toggle stuff by hiding an html checkbox. You can learn more about it [here](https://css-tricks.com/the-checkbox-hack/)

# HTML
### Learn how to use ```<div>``` elements
These are super important. Put the content of your webpage in one and the header in one. This way you can style the whole webpage at a time, which is a nightmare without them.
```html
<div class="everything">
    <h1>Header</h1>
    <p>Lorem ipsum stupid placeholder textum</p>
</div>
### Use HTML tables
HTML tables are super useful for arranging text and content neatly on a page, this is a nice alternative to the
```css
* {
    column-count: 2;
}
```
property in CSS.
```html
<table>
    <td> <!-- A row -->
        <tr> Content </tr>
        <tr> Another cell to the right </tr>
    <td> <!-- End that row -->
    <td> <!-- Add another row directly underneath -->
        <tr>More stuff</tr> <!-- This is directly underneath the cell with 'content' in it -->
        <tr> Another cell below the one which is to the right lol</tr>
    </td>
</table>
```
### Learn to comment your code as a habit
Commenting code is important if you want anyone else to know what the heck it does, it's also super usefull for navigating around your code.
```css
/* A CSS comment */
```
``` html
<!-- An HTML comment -->
```
### Learn to use iframes
iframes are basically an embedded window of another webpage. These are super useful for repeating any code, e.g. a header, a JS graph, or anything that would clutter your code if you put it directly in your code.
```html
<iframe src="webpage that you're embedding" scrolling="no" width="width goes here" height="height goes here"></iframe>
<!-- It is important to close the iframe tag. -->
```
